# Auto-generated by .github/workflows/release.yml.
# Hand-edits will be overwritten on the next release.
#
# Source of truth: this file in the InLook repo. The StruisICT/homebrew-tap
# repo mirrors it at Casks/inlook.rb.
cask "inlook" do
  version "1.0.0"
  sha256 "ff093ebac40c3dd59b6a42851365f178c6ce6978c13607aecd4e20ed81f16c80"

  url "https://github.com/StruisICT/InLook/releases/download/v#{version}/InLook-#{version}-universal.dmg"
  name "InLook"
  desc "Fast, free .eml email viewer"
  homepage "https://github.com/StruisICT/InLook"

  app "InLook.app"

  zap trash: [
    "~/Library/Preferences/nl.struisict.inlook.plist",
    "~/Library/Saved Application State/nl.struisict.inlook.savedState",
  ]
end
