# Auto-generated by .github/workflows/release.yml.
# Hand-edits will be overwritten on the next release.
#
# Source of truth: this file in the InLook repo. The StruisICT/homebrew-tap
# repo mirrors it at Casks/inlook.rb.
cask "inlook" do
  version "1.1.2"
  sha256 "b1b1ccc1e0dfdee0e711711708b361f91e69b43a53c9cf2bfdfc0ca917e2de58"

  url "https://github.com/StruisICT/InLook/releases/download/v#{version}/InLook-#{version}-universal.dmg"
  name "InLook"
  desc "Fast, free .eml email viewer"
  homepage "https://github.com/StruisICT/InLook"

  app "InLook.app"

  zap trash: [
    "~/Library/Preferences/nl.struisict.inlook.plist",
    "~/Library/Saved Application State/nl.struisict.inlook.savedState",
  ]
end
