# Auto-generated by .github/workflows/release.yml.
# Hand-edits will be overwritten on the next release.
#
# Source of truth: this file in the InLook repo. The StruisICT/homebrew-tap
# repo mirrors it at Casks/inlook.rb.
cask "inlook" do
  version "1.2.0"
  sha256 "8e3a4b1c206cf385b34e215d440d9a252e692bd8324b3c53f5274e1462e1e34a"

  url "https://github.com/StruisICT/InLook/releases/download/v#{version}/InLook-#{version}-universal.dmg"
  name "InLook"
  desc "Fast, free .eml email viewer"
  homepage "https://github.com/StruisICT/InLook"

  app "InLook.app"

  zap trash: [
    "~/Library/Preferences/nl.struisict.inlook.plist",
    "~/Library/Saved Application State/nl.struisict.inlook.savedState",
  ]
end
